### ISSUE TITLE
StatusRequest of specific messages fails

### ISSUE THREAD

**Issue by bsandmann** [roots-id/didcomm-mediator#22]
I'm getting a db error when trying to execute get_message_status for a specific recipient. Getting the message status for all recipients works fine. I'm not so familiar with mongoDb: but maybe the "attachment:1" part is not nessescary here?

db_utils.py: Line 126
```def get_message_status(remote_did, recipient_key):
    if recipient_key:
        # FIX validate that recipient_key belongs to remote_did
        count = db.messages.count_documents({"recipient_key": recipient_key},{"attachment":1})
    else: ...```

**Comment by rodolfomiranda** [comment]
As you pointed out, there was an error that was fixed in the last commit https://github.com/roots-id/didcomm-mediator/commit/8aa0fc4e078d6a8dc452eaaba2220de0804de03a

**Comment by bsandmann** [comment]
This is an unrelated issue, I haven't mentioned yesterday. Requesting a the message-status for an specific DID still fails. But I believe it's easy fix.

**Comment by rodolfomiranda** [comment]
new fix in https://github.com/roots-id/didcomm-mediator/commit/6cf0b2c1a8fded86e56d7fc67d055b69113f4f65
